### ISSUE TITLE
go run  golang程序的时候报错

### ISSUE THREAD

**Issue by erha367** [chenzhuoyu/iasm#1]
(base) [root@yangsen08 luna-core]# go run core.go -f etc/app_dev.yaml 
github.com/chenzhuoyu/iasm/x86_64: /root/data/go/pkg/tool/linux_amd64/compile: signal: killed

**Comment by flyhope** [comment]
这玩易特耗内存，有可能是被OOM了，解决方案：

1. 增加机器内存
2. 确保GOGC环境变量打开，尝试将值调小，通过GC降低内存占用。

**Comment by echoturing** [comment]
我aws 的 2c2g 主机直接卡住。。。看起来确实是内存耗尽了
<img width="667" alt="image" src="https://github.com/chenzhuoyu/iasm/assets/11382552/1b3f779d-89f5-4226-b7a8-2dbad7b38f8e">

**Comment by chenzhuoyu** [comment]
@erha367 这是什么 issue，怎么提到我这来了。。。
@flyhope 你说的耗内存，能详细说说吗？

**Comment by chenzhuoyu** [comment]
Closed due to lack of response.
