### ISSUE TITLE
v0.9.0: unknown revision 

### ISSUE THREAD

**Issue by bagastri07** [chenzhuoyu/iasm#2]
I encounter this issue 
```bash
go: github.com/bytedance/sonic@v1.10.2 requires
        github.com/chenzhuoyu/iasm@v0.9.0: reading github.com/chenzhuoyu/iasm/go.mod at revision v0.9.0: unknown revision v0.9.0
```

when I saw the package it self in github repository I don't see any release here

**Comment by derekssmith** [comment]
+1 I am getting this for v0.9.1

**Comment by ntauth** [comment]
Same issue here with v0.9.1

**Comment by nishant8568** [comment]
I'm getting the same issue with v0.9.1

**Comment by bagastri07** [comment]
I have the solution. If you are using Gin, gin-cors, or any dependencies that use iasm directly or indirectly, just update these dependencies to the latest version. In my case, simply run the following commands:

```bash
go get -u github.com/gin-gonic/gin  
go get -u github.com/gin-contrib/cors
```

GoodLuck^^

**Comment by sunggun-yu** [comment]
please check your GOPROXY. it fails if it is `direct` only.

```bash
go env GOPROXY
```

check your global env var or set `GOPROXY`

```bash
export GOPROXY=https://proxy.golang.org,direct
```

```bash
go env -w GOPROXY='https://proxy.golang.org,direct'
```

**Comment by ntauth** [comment]
> I have the solution. If you are using Gin, gin-cors, or any dependencies that use iasm directly or indirectly, just update these dependencies to the latest version. In my case, simply run the following commands:
> 
> ```shell
> go get -u github.com/gin-gonic/gin  
> go get -u github.com/gin-contrib/cors
> ```
> 
> it happen likely because these dependencies migrate to `https://github.com/cloudwego/iasm` if you looking at these go.mod
> 
> GoodLuck^^

That was indeed the issue, thanks!

**Comment by chenzhuoyu** [comment]
Project moved to [https://github.com/cloudwego/iasm](https://github.com/cloudwego/iasm), this repo is no longer suitable for production use.

**Comment by zhaoliangainannan** [comment]
I meet same problem,and then I find that the reason is my bash_profile config has add a new GOPROXY,just delete it

**Comment by solutionstack** [comment]
> export GOPROXY=https://proxy.golang.org,direct

This!, thanks
